services:
  silverbullet:
    image: zefhemel/silverbullet
    container_name: silverbullet
    restart: unless-stopped
    ## To enable additional options, such as authentication, set environment variables, e.g.
    #environment:
    #- SB_USER=angel:1234
    volumes:
      - space:/space
    ports:
      - ${PORT}:3000
volumes:
  space:
